### ISSUE TITLE
[Improvement]: Provide install documentation

### ISSUE THREAD

**Issue by ncordonnier-datasolution** [pimcore/number-sequence-generator#17]
### Improvement description

Hello,
I would like to install this interesting bundle but I can figure out how to do it.  
It seems we can apply the `pimcore:bundle:install` on this bundle.

Could you describe the install process of this bundle into the README file or just explain it to me and I would update the README please?
Cheers.

Nicolas

**Comment by mattamon** [comment]
@ncordonnier-datasolution I added the docs here #21

**Comment by mattamon** [comment]
Solved by #21

**Comment by ncordonnier-datasolution** [comment]
> @ncordonnier-datasolution I added the docs here #21

Perfect, thank you 🤝
