### ISSUE TITLE
[Improvement/support]: README.md example update

### ISSUE THREAD

**Issue by sissonen** [pimcore/number-sequence-generator#5]
### Improvement description

Using the number-sequence-generator as it is suggested in the readme.md file, results in an error:

`The "Pimcore\Bundle\NumberSequenceGeneratorBundle\Generator" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.`

I tried using the generator as follows:

```
namespace App\EventListener;

use Pimcore\Event\Model\DataObjectEvent;
use Pimcore\Model\DataObject\Product;

class ProductCodeSettingListener
{
    public function onPreAdd(DataObjectEvent $event) 
    {
        $object = $event->getObject();

        if ($object instanceof Product) {
            $generator = \Pimcore::getContainer()->get(\Pimcore\Bundle\NumberSequenceGeneratorBundle\Generator::class);
            $object->setProductCode($generator->getNext('productcode', 50000));
        }
    }
}
```

I suppose there has been a change on how Symfony handles services (they are not public by default), maybe that is the reason the suggested way is not working? Or maybe I should do something more in the event listener?

**Comment by dvesh3** [comment]
@sissonen have you tried using DI way?
```php
class ProductCodeSettingListener
{
    public function __construct(protected Generator $generator)
    {
    }
```

**Comment by sissonen** [comment]
I suppose my issue was with how to do it the DI way :)

This seemed to do the trick:

```
namespace App\EventListener;

use Pimcore\Event\Model\DataObjectEvent;
use Pimcore\Model\DataObject\Product;
use Pimcore\Bundle\NumberSequenceGeneratorBundle\Generator;

class ProductCodeSettingListener
{
    protected $generatorService;

    public function __construct(protected Generator $generator) {
        $this->generatorService = $generator;
    }
    
    public function onPreAdd(DataObjectEvent $event) 
    {
        $object = $event->getObject();

        if ($object instanceof Product) {
            $object->setProductCode($this->generatorService->getNext('productcode', 50000));
        }
    }
}
```

Maybe an update to the readme example would be in order?

Thanks @dvesh3 !

**Comment by dvesh3** [comment]
> Maybe an update to the readme example would be in order?

Done 😉
